# Используем официальный образ Python
FROM python:3.12

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файлы проекта в контейнер
COPY . .

# Устанавливаем Poetry (менеджер зависимостей Python)
RUN pip install poetry

# Устанавливаем зависимости через Poetry
RUN poetry install 

# Команда для запуска контейнера
CMD ["poetry", "run", "python", "seed.py"]
